from pathlib import Path
p=Path('/home/ubuntu/tonan-study')

db=p/'server/db.ts'
s=db.read_text()
s=s.replace('const [sessions, progress, events] = await Promise.all([','const [sessions, progress, dueProgress, events] = await Promise.all([')
s=s.replace('entryIds.length ? db.select().from(studyProgress).where(and(eq(studyProgress.learnerId, learner.id), inArray(studyProgress.entryId, entryIds), gte(studyProgress.lastReviewedAt, start), lte(studyProgress.lastReviewedAt, end))) : Promise.resolve([]),\n    db.select().from(learnerEvents)', 'entryIds.length ? db.select().from(studyProgress).where(and(eq(studyProgress.learnerId, learner.id), inArray(studyProgress.entryId, entryIds), gte(studyProgress.lastReviewedAt, start), lte(studyProgress.lastReviewedAt, end))) : Promise.resolve([]),\n    entryIds.length ? db.select().from(studyProgress).where(and(eq(studyProgress.learnerId, learner.id), inArray(studyProgress.entryId, entryIds), gte(studyProgress.nextReviewAt, start), lte(studyProgress.nextReviewAt, end))) : Promise.resolve([]),\n    db.select().from(learnerEvents)')
s=s.replace('return { date, totalSeconds: sessions.reduce((sum, item) => sum + item.seconds, 0), learned, retention, events };','return { date, totalSeconds: sessions.reduce((sum, item) => sum + item.seconds, 0), learned, retention, reviewDue: dueProgress.length, events };')
s=s.replace('export async function deleteRecommendedTest(password: string, testId: number) {','export async function deleteCalendarEvent(password: string, eventId: number) {\n  await requireAdminPassword(password);\n  const db = await getDb();\n  if (!db) throw new Error("Database unavailable");\n  await db.delete(calendarEvents).where(eq(calendarEvents.id, eventId));\n}\n\nexport async function deleteRecommendedTest(password: string, testId: number) {')
s=s.replace('mistakeEntryIds: relevantProgress.filter(item => item.incorrectCount > 0).sort((left, right) => right.incorrectCount - left.incorrectCount).map(item => item.entryId),','mistakeEntryIds: relevantProgress.filter(item => item.incorrectCount > 0).sort((left, right) => right.incorrectCount - left.incorrectCount).map(item => item.entryId),\n    reviewDates: relevantProgress.filter(item => item.nextReviewAt).map(item => item.nextReviewAt),')
db.write_text(s)

r=p/'server/routers.ts'
s=r.read_text()
s=s.replace('deleteRecommendedTest,','deleteRecommendedTest,\n  deleteCalendarEvent,')
s=s.replace('deleteRecommendedTest: publicProcedure.input(z.object({ password: z.string(), testId: z.number().int().positive() })).mutation(({ input }) => deleteRecommendedTest(input.password, input.testId)),','deleteRecommendedTest: publicProcedure.input(z.object({ password: z.string(), testId: z.number().int().positive() })).mutation(({ input }) => deleteRecommendedTest(input.password, input.testId)),\n    deleteCalendarEvent: publicProcedure.input(z.object({ password: z.string(), eventId: z.number().int().positive() })).mutation(({ input }) => deleteCalendarEvent(input.password, input.eventId)),')
r.write_text(s)

h=p/'client/src/pages/Home.tsx'
s=h.read_text()
s=s.replace('function CalendarGrid({ sessions, events, onSelect }: { sessions: { createdAt: Date }[]; events: { eventDate: string; title: string }[]; onSelect: (date: string) => void }) {','function CalendarGrid({ sessions, events, reviewDates, onSelect }: { sessions: { createdAt: Date }[]; events: { eventDate: string; title: string }[]; reviewDates: (Date | string | null)[]; onSelect: (date: string) => void }) {')
s=s.replace('const sessionDays = new Set(sessions.map(item => format(new Date(item.createdAt), "yyyy-MM-dd")));','const sessionDays = new Set(sessions.map(item => format(new Date(item.createdAt), "yyyy-MM-dd")));\n  const reviewDaySet = new Set(reviewDates.filter(Boolean).map(date => format(new Date(date as Date | string), "yyyy-MM-dd")));',1)
s=s.replace('function CalendarGardenPager({ pin, category, sessions, events }: { pin: string; category: Category; sessions: { createdAt: Date }[]; events: { eventDate: string; title: string }[] }) {','function CalendarGardenPager({ pin, category, sessions, events, reviewDates }: { pin: string; category: Category; sessions: { createdAt: Date }[]; events: { eventDate: string; title: string }[]; reviewDates: (Date | string | null)[] }) {')
s=s.replace('<CalendarGrid sessions={sessions} events={events} onSelect={setSelectedDate} />','<CalendarGrid sessions={sessions} events={events} reviewDates={reviewDates} onSelect={setSelectedDate} />')
s=s.replace('{learned ? <Sprout className="h-4 w-4" /> : <span>{date.getDate()}</span>}{event &&', '{learned ? <Sprout className="h-4 w-4" /> : <span>{date.getDate()}</span>}{reviewDaySet.has(key) && <RotateCcw className="absolute right-1 top-1 h-3 w-3 text-violet-500" title="SRS復習予定" />}{event &&',1)
s=s.replace('sessions={data.sessions} events={[...data.events, ...(data.personalEvents ?? [])]} />','sessions={data.sessions} events={[...data.events, ...(data.personalEvents ?? [])]} reviewDates={data.reviewDates ?? []} />')
s=s.replace('reviewDue: dueProgress.length, events', 'reviewDue: dueProgress.length, events')
s=s.replace('<p className="text-[10px] text-muted-foreground">定着率</p></div></div><div className="space-y-2">','<p className="text-[10px] text-muted-foreground">定着率</p></div></div>{detail.data.reviewDue > 0 && <div className="flex items-center gap-2 rounded-xl bg-violet-50 p-3 text-sm dark:bg-violet-950/25"><RotateCcw className="h-4 w-4 text-violet-600" />SRS復習予定：{detail.data.reviewDue}件</div>}<div className="space-y-2">',1)
s=s.replace('const addEvent = trpc.admin.addCalendarEvent.useMutation', 'const deleteEvent = trpc.admin.deleteCalendarEvent.useMutation({ onSuccess: async () => { toast.success("管理イベントを削除しました"); await utils.admin.overview.invalidate(); await utils.learning.dashboard.invalidate(); }, onError: error => toast.error(error.message) });\n  const addEvent = trpc.admin.addCalendarEvent.useMutation',1)
# Insert admin event/history cards before standard-book card.
needle='<Card><CardHeader className="pb-3"><CardTitle className="text-base">2026年度標準単語帳</CardTitle>'
insert='<Card><CardHeader className="pb-3"><CardTitle className="text-base">管理イベント一覧</CardTitle><CardDescription>公開中のカレンダーイベントを削除できます。</CardDescription></CardHeader><CardContent className="space-y-2">{data.events.length ? data.events.map((item: any) => <div key={item.id} className="flex items-center gap-2 rounded-xl bg-muted/60 p-3"><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{item.title}</p><p className="text-xs text-muted-foreground">{item.eventDate} ／ {item.category === "both" ? "共通" : categoryLabel[item.category as Category]}</p></div><Button size="sm" variant="outline" onClick={() => window.confirm("このイベントを削除しますか？") && deleteEvent.mutate({ password, eventId: item.id })}>削除</Button></div>) : <p className="text-sm text-muted-foreground">管理イベントはありません。</p>}</CardContent></Card><Card><CardHeader className="pb-3"><CardTitle className="text-base">配信履歴</CardTitle><CardDescription>お知らせとおすすめテストの配信履歴です。</CardDescription></CardHeader><CardContent className="max-h-64 space-y-2 overflow-y-auto">{[...data.announcements.map((item: any) => ({ id: `a-${item.id}`, title: item.title, detail: item.body, createdAt: item.createdAt, kind: "お知らせ" })), ...data.tests.map((item: any) => ({ id: `t-${item.id}`, title: item.title, detail: `${item.startDate}〜${item.endDate} ／ No.${item.startNo}〜${item.endNo}`, createdAt: item.createdAt, kind: "おすすめテスト" }))].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()).map(item => <div key={item.id} className="rounded-xl bg-muted/60 p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm font-semibold">{item.title}</p><Badge variant="outline">{item.kind}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{item.detail}</p><p className="mt-1 text-[10px] text-muted-foreground">{new Date(item.createdAt).toLocaleString()}</p></div>)}{!data.announcements.length && !data.tests.length && <p className="text-sm text-muted-foreground">配信履歴はありません。</p>}</CardContent></Card>'+needle
s=s.replace(needle,insert,1)
# Add explicit writing judgment assistance around the existing revealed answer.
s=s.replace('<p className="text-center text-sm font-semibold">正解：{current.writingAnswer || current.front}</p><div className="grid grid-cols-2 gap-2">','<div className="rounded-xl border border-violet-200 bg-violet-50 p-3 text-center dark:border-violet-900 dark:bg-violet-950/25"><p className="text-xs font-semibold text-violet-700 dark:text-violet-300">正誤判定の補助</p><p className="mt-1 text-xs text-muted-foreground">書いた字と見本の形・部首・読みを見比べて判定してください。</p><p className="mt-2 text-2xl font-bold">{current.writingAnswer || current.front}</p></div><div className="grid grid-cols-2 gap-2">',1)
h.write_text(s)
