from pathlib import Path
import re

path = Path('/home/ubuntu/tonan-study/client/src/pages/Home.tsx')
s = path.read_text()
start = s.index('function AdminWorkspace')
end = s.index('\nfunction AdminPage', start)
new = r'''function AdminWorkspace({ password, data, loading }: { password: string; data: any; loading: boolean }) {
  const utils = trpc.useUtils();
  const [notice, setNotice] = useState({ title: "", body: "" });
  const [event, setEvent] = useState({ eventDate: "", title: "", category: "both" as "english" | "kanji" | "both" });
  const [word, setWord] = useState<{ id?: number; bookId: string; entryNo: string; front: string; back: string; writingAnswer: string }>({ bookId: "", entryNo: "", front: "", back: "", writingAnswer: "" });
  const [recommended, setRecommended] = useState({ title: "", category: "english" as Category, bookId: "", startNo: "1", endNo: "10", questionCount: "10", startDate: "", endDate: "" });
  const announce = trpc.admin.publishAnnouncement.useMutation({ onSuccess: async () => { setNotice({ title: "", body: "" }); toast.success("お知らせを配信しました"); await utils.admin.overview.invalidate(); await utils.learning.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const addEvent = trpc.admin.addCalendarEvent.useMutation({ onSuccess: async () => { setEvent({ eventDate: "", title: "", category: "both" }); toast.success("カレンダーイベントを追加しました"); await utils.admin.overview.invalidate(); await utils.learning.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const saveWord = trpc.admin.saveStandardEntry.useMutation({ onSuccess: async () => { setWord({ bookId: "", entryNo: "", front: "", back: "", writingAnswer: "" }); toast.success("標準単語帳を更新しました"); await utils.admin.overview.invalidate(); await utils.learning.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const deleteWord = trpc.admin.deleteStandardEntry.useMutation({ onSuccess: async () => { setWord({ bookId: "", entryNo: "", front: "", back: "", writingAnswer: "" }); toast.success("単語を削除しました"); await utils.admin.overview.invalidate(); await utils.learning.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const publishTest = trpc.admin.publishRecommendedTest.useMutation({ onSuccess: async () => { setRecommended({ title: "", category: "english", bookId: "", startNo: "1", endNo: "10", questionCount: "10", startDate: "", endDate: "" }); toast.success("おすすめテストを配信しました。ホームのお知らせにも表示されます"); await utils.admin.overview.invalidate(); await utils.learning.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const deleteTest = trpc.admin.deleteRecommendedTest.useMutation({ onSuccess: async () => { toast.success("おすすめテストを削除しました"); await utils.admin.overview.invalidate(); await utils.learning.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const downloadBook = (bookId: number, category: Category, name: string) => { const rows = data.entries.filter((item: { bookId: number }) => item.bookId === bookId).sort((a: { entryNo: number }, b: { entryNo: number }) => a.entryNo - b.entryNo); const quote = (value: string) => `"${value.replace(/"/g, '""')}"`; const header = category === "english" ? "英単語,意味" : "漢字,読み,書き取り答え"; const body = rows.map((item: any) => category === "english" ? [item.back, item.front] : [item.front, item.back, item.writingAnswer || item.front]).map((row: string[]) => row.map(quote).join(",")).join("\\n"); downloadTextFile(`${name.replace(/[^a-zA-Z0-9ぁ-んァ-ン一-龠_-]/g, "_")}.csv`, `\\uFEFF${header}\\n${body}\\n`); };
  if (loading) return <Card><CardContent className="p-8 text-center text-sm text-muted-foreground">読み込み中…</CardContent></Card>;
  return <div className="space-y-4 pb-2"><div className="pt-1"><p className="text-xs font-semibold tracking-wider text-primary">ADMINISTRATION</p><h1 className="mt-1 text-2xl font-bold">配信と編集</h1><p className="mt-1 text-sm text-muted-foreground">共有内容、標準単語帳、配信中テストを管理します。</p></div>
+  <Card><CardHeader className="pb-3"><CardTitle className="text-base">お知らせを配信</CardTitle></CardHeader><CardContent className="space-y-2"><Input placeholder="タイトル" value={notice.title} onChange={e => setNotice({ ...notice, title: e.target.value })} /><Textarea placeholder="ホーム画面に表示するメッセージ" value={notice.body} onChange={e => setNotice({ ...notice, body: e.target.value })} /><Button className="w-full" disabled={!notice.title || !notice.body} onClick={() => announce.mutate({ password, ...notice })}><Send className="mr-2 h-4 w-4" />配信する</Button></CardContent></Card>
+  <Card><CardHeader className="pb-3"><CardTitle className="text-base">おすすめテストを配信</CardTitle><CardDescription>各数字に項目名を付けています。配信期間中だけ学習者に表示されます。</CardDescription></CardHeader><CardContent className="space-y-2"><Input placeholder="テスト名" value={recommended.title} onChange={e => setRecommended({ ...recommended, title: e.target.value })} /><Select value={recommended.category} onValueChange={(value: Category) => setRecommended({ ...recommended, category: value, bookId: "" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="english">英単語</SelectItem><SelectItem value="kanji">漢字</SelectItem></SelectContent></Select><Select value={recommended.bookId} onValueChange={bookId => setRecommended({ ...recommended, bookId })}><SelectTrigger><SelectValue placeholder="単語帳" /></SelectTrigger><SelectContent>{data.books.filter((book: { category: Category }) => book.category === recommended.category).map((book: { id: number; name: string }) => <SelectItem key={book.id} value={String(book.id)}>{book.name}</SelectItem>)}</SelectContent></Select><div className="grid grid-cols-3 gap-2"><label className="text-xs text-muted-foreground">開始No.<Input type="number" min="1" value={recommended.startNo} onChange={e => setRecommended({ ...recommended, startNo: e.target.value })} /></label><label className="text-xs text-muted-foreground">終了No.<Input type="number" min="1" value={recommended.endNo} onChange={e => setRecommended({ ...recommended, endNo: e.target.value })} /></label><label className="text-xs text-muted-foreground">問題数<Input type="number" min="1" value={recommended.questionCount} onChange={e => setRecommended({ ...recommended, questionCount: e.target.value })} /></label></div><div className="grid grid-cols-2 gap-2"><label className="text-xs text-muted-foreground">配信開始日<Input type="date" value={recommended.startDate} onChange={e => setRecommended({ ...recommended, startDate: e.target.value })} /></label><label className="text-xs text-muted-foreground">配信終了日<Input type="date" value={recommended.endDate} onChange={e => setRecommended({ ...recommended, endDate: e.target.value })} /></label></div><Button className="w-full" variant="outline" disabled={!recommended.title || !recommended.bookId || !recommended.startDate || !recommended.endDate} onClick={() => publishTest.mutate({ password, title: recommended.title, category: recommended.category, bookId: Number(recommended.bookId), startNo: Number(recommended.startNo), endNo: Number(recommended.endNo), questionCount: Number(recommended.questionCount), startDate: recommended.startDate, endDate: recommended.endDate })}><Crown className="mr-2 h-4 w-4" />おすすめテストを配信</Button></CardContent></Card>
+  <Card><CardHeader className="pb-3"><CardTitle className="text-base">配信中のおすすめテスト</CardTitle></CardHeader><CardContent className="space-y-2">{data.tests.length ? data.tests.map((test: any) => <div key={test.id} className="flex items-center gap-3 rounded-xl bg-muted/60 p-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{test.title}</p><p className="text-xs text-muted-foreground">{test.startDate}〜{test.endDate} ／ No.{test.startNo}〜{test.endNo} ／ 問題数 {test.questionCount}</p></div><Button size="sm" variant="outline" onClick={() => { if (window.confirm("このおすすめテストを削除しますか？")) deleteTest.mutate({ password, testId: test.id }); }}>削除</Button></div>) : <p className="text-sm text-muted-foreground">現在配信中のテストはありません。</p>}</CardContent></Card>
+  <Card><CardHeader className="pb-3"><CardTitle className="text-base">カレンダーイベント</CardTitle></CardHeader><CardContent className="space-y-2"><Input type="date" value={event.eventDate} onChange={e => setEvent({ ...event, eventDate: e.target.value })} /><Input placeholder="例：模試の日" value={event.title} onChange={e => setEvent({ ...event, title: e.target.value })} /><Select value={event.category} onValueChange={(value: "english" | "kanji" | "both") => setEvent({ ...event, category: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="both">英単語・漢字 共通</SelectItem><SelectItem value="english">英単語</SelectItem><SelectItem value="kanji">漢字</SelectItem></SelectContent></Select><Button className="w-full" variant="outline" disabled={!event.eventDate || !event.title} onClick={() => addEvent.mutate({ password, ...event })}><CalendarDays className="mr-2 h-4 w-4" />追加する</Button></CardContent></Card>
+  <Card><CardHeader className="pb-3"><CardTitle className="text-base">2026年度標準単語帳</CardTitle><CardDescription>CSVは英語では「英単語,意味」、漢字では「漢字,読み,書き取り答え」で出力します。</CardDescription></CardHeader><CardContent className="space-y-3">{data.books.map((book: { id: number; category: Category; name: string }) => <div key={book.id} className="rounded-xl border p-3"><div className="mb-2 flex items-center justify-between"><p className="text-sm font-semibold">{categoryLabel[book.category]}：{book.name}</p><Button size="sm" variant="outline" onClick={() => downloadBook(book.id, book.category, book.name)}>CSVダウンロード</Button></div><div className="max-h-48 space-y-1 overflow-y-auto">{data.entries.filter((item: { bookId: number }) => item.bookId === book.id).map((item: any) => <div key={item.id} className="flex items-center gap-2 rounded-lg bg-muted/50 px-2 py-1.5"><button className="min-w-0 flex-1 truncate text-left text-xs" onClick={() => setWord({ id: item.id, bookId: String(item.bookId), entryNo: String(item.entryNo), front: item.front, back: item.back, writingAnswer: item.writingAnswer ?? "" })}>No.{item.entryNo} {item.front} / {item.back}</button><Button size="sm" variant="ghost" onClick={() => { if (window.confirm("この単語を削除しますか？")) deleteWord.mutate({ password, entryId: item.id }); }}>削除</Button></div>)}</div></div>)}</CardContent></Card>
+  <Card><CardHeader className="pb-3"><CardTitle className="text-base">標準単語を編集</CardTitle></CardHeader><CardContent className="space-y-2"><Input value={word.bookId} readOnly placeholder="編集対象は一覧から選択" /><Input type="number" min="1" placeholder="No." value={word.entryNo} onChange={e => setWord({ ...word, entryNo: e.target.value })} /><Input placeholder="日本語・漢字" value={word.front} onChange={e => setWord({ ...word, front: e.target.value })} /><Input placeholder="英語・読み方" value={word.back} onChange={e => setWord({ ...word, back: e.target.value })} /><Button className="w-full" disabled={!word.id || !word.entryNo || !word.front || !word.back} onClick={() => saveWord.mutate({ password, id: word.id, bookId: Number(word.bookId), entryNo: Number(word.entryNo), front: word.front, back: word.back, writingAnswer: word.writingAnswer || null })}>編集内容を保存</Button></CardContent></Card>
+  </div>;
+}'''
# Remove accidental patch-prefix characters from the raw JSX block.
new = new.replace('\n+  ', '\n  ')
s = s[:start] + new + s[end:]
# Add personal-book deletion to the existing BooksPage when its mutation list is declared.
s = s.replace('const importEntries = trpc.learning.importEntries.useMutation', 'const deleteBook = trpc.learning.deletePersonalBook.useMutation({ onSuccess: async () => { toast.success("マイ単語帳を削除しました"); await utils.learning.dashboard.invalidate(); setSelectedBook(data.books.find((book: any) => book.kind === "standard")?.id ?? null); }, onError: error => toast.error(error.message) });\n  const importEntries = trpc.learning.importEntries.useMutation', 1)
# Add a deletion affordance to the selected-book header if present.
s = s.replace('<CardDescription>{entries.data?.length ?? 0} 語を登録</CardDescription></div>', '<CardDescription>{entries.data?.length ?? 0} 語を登録</CardDescription></div>{selected?.kind === "personal" && <Button size="sm" variant="outline" onClick={() => selectedBook && window.confirm("このマイ単語帳を削除しますか？") && deleteBook.mutate({ pin, bookId: selectedBook })}>単語帳を削除</Button>', 1)
path.write_text(s)
