from pathlib import Path
p=Path('/home/ubuntu/tonan-study/client/src/pages/Home.tsx')
s=p.read_text()
s=s.replace('CSVは英語では「英単語,意味」、漢字では「漢字,読み,書き取り答え」で出力します。','英単語・漢字ともCSVを選択して、最大3,000語まで確認して取り込めます。取り込み時は選択した標準単語帳の内容を置き換えます。')
s=s.replace('<Button size="sm" variant="outline" onClick={() => downloadBook(book.id, book.category, book.name)}>CSVダウンロード</Button>','<label className="inline-flex cursor-pointer items-center rounded-md border border-input bg-background px-3 py-2 text-xs font-medium shadow-sm transition hover:bg-accent hover:text-accent-foreground">CSVアップロード<Input type="file" accept=".csv,text/csv" className="hidden" onChange={e => { const file = e.target.files?.[0]; if (file) prepareStandardUpload(book.id, book.category, file); e.currentTarget.value = ""; }} /></label>')
old='<div className="max-h-48 space-y-1 overflow-y-auto">{data.entries.filter((item: { bookId: number }) => item.bookId === book.id).map((item: any) => <div key={item.id} className="flex items-center gap-2 rounded-lg bg-muted/50 px-2 py-1.5"><button className="min-w-0 flex-1 truncate text-left text-xs" onClick={() => setWord({ id: item.id, bookId: String(item.bookId), entryNo: String(item.entryNo), front: item.front, back: item.back, writingAnswer: item.writingAnswer ?? "" })}>No.{item.entryNo} {item.front} / {item.back}</button><Button size="sm" variant="ghost" onClick={() => { if (window.confirm("この単語を削除しますか？")) deleteWord.mutate({ password, entryId: item.id }); }}>削除</Button></div>)}</div>'
new='<div className="max-h-48 space-y-1 overflow-y-auto">{data.entries.filter((item: { bookId: number }) => item.bookId === book.id).map((item: any) => <div key={item.id} className="flex items-center gap-2 rounded-lg bg-muted/50 px-2 py-1.5"><button className="min-w-0 flex-1 truncate text-left text-xs" onClick={() => setWord({ id: item.id, bookId: String(item.bookId), entryNo: String(item.entryNo), front: item.front, back: item.back, writingAnswer: item.writingAnswer ?? "" })}>No.{item.entryNo} {item.front} / {item.back}</button><Button size="sm" variant="ghost" onClick={() => { if (window.confirm("この単語を削除しますか？")) deleteWord.mutate({ password, entryId: item.id }); }}>削除</Button></div>)}</div>{Array.from(new Set(data.entries.filter((item: any) => item.bookId === book.id && item.importBatchId).map((item: any) => item.importBatchId))).map(batchId => <div key={batchId} className="mt-2 flex items-center justify-between rounded-lg border border-dashed p-2"><span className="text-xs text-muted-foreground">CSVアップロード分（{data.entries.filter((item: any) => item.bookId === book.id && item.importBatchId === batchId).length}語）</span><Button size="sm" variant="outline" onClick={() => window.confirm("このCSVアップロード分をまとめて削除しますか？") && deleteImportBatch.mutate({ password, bookId: book.id, batchId })}>アップロード分を削除</Button></div>)}'
if old not in s: raise SystemExit('standard list pattern not found')
s=s.replace(old,new,1)
needle='<Card><CardHeader className="pb-3"><CardTitle className="text-base">2026年度標準単語帳</CardTitle>'
preview='<>{standardUpload && <Card className="border-primary/30 bg-primary/5"><CardHeader className="pb-2"><CardTitle className="text-base">CSV取込の確認</CardTitle><CardDescription>{standardUpload.filename} ／ {standardUpload.entries.length}語。英単語・漢字の列を確認してから取り込みます。</CardDescription></CardHeader><CardContent><div className="max-h-32 divide-y overflow-y-auto rounded-lg border bg-background px-2">{standardUpload.entries.slice(0, 5).map((item, index) => <div key={`${item.front}-${index}`} className="grid grid-cols-2 gap-2 py-2 text-xs"><span className="truncate">{item.front}</span><span className="truncate text-muted-foreground">{item.back}</span></div>)}</div><div className="mt-3 flex gap-2"><Button variant="outline" className="flex-1" onClick={() => setStandardUpload(null)}>取消</Button><Button className="flex-1" disabled={importStandard.isPending} onClick={() => importStandard.mutate({ password, bookId: standardUpload.bookId, entries: standardUpload.entries })}>この内容で取り込む</Button></div></CardContent></Card>}</>'+needle
s=s.replace(needle,preview,1)
p.write_text(s)
